### ISSUE TITLE
Receipt not available for 'To' block

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/trader#129]
The following issue was reported by @jmoreira-valory when the trader agent tried to filter some blocks.

```
Message(sender=valory/ledger:0.19.0,to=valory/trader_abci:0.1.0,code=500,data=b'',dialogue_reference=('43ed62ba995b9ae21f979ae548b39ea088badd5839c2009d5e9a1048c70a2aab', 'c7fd1bfb7833327dfe6af0ea94e6cc94d2acb88803cf8b648112cd835b5e4cd6'),message=Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/web3/manager.py", line 288, in formatted_response
    raise ValueError(error)
ValueError: {'code': -32001, 'message': "Receipt not available for 'To' block '30865797'."}
[2023-11-09 09:16:26,638][ERROR] [agent] Could not successfully interact with the valory/conditional_tokens:0.1.0 contract using 'check_redeemed': Message(sender=valory/ledger:0.19.0,to=valory/trader_abci:0.1.0,code=500,data=b'',dialogue_reference=('43ed62ba995b9ae21f979ae548b39ea088badd5839c2009d5e9a1048c70a2aab', 'c7fd1bfb7833327dfe6af0ea94e6cc94d2acb88803cf8b648112cd835b5e4cd6'),message=Traceback (most recent call last):
,message_id=-1,performative=error,target=1)
[2023-11-09 09:16:26,638] [INFO] [agent] Retrying in 1 seconds.
  File "/usr/local/lib/python3.11/site-packages/web3/manager.py", line 288, in formatted_response
    raise ValueError(error)
ValueError: {'code': -32001, 'message': "Receipt not available for 'To' block '30865797'."}
```

**Comment by Adamantios** [comment]
This can happen when the RPC is misbehaving. We have noticed this sometimes when using quicknode on Gnosis chain.

**Comment by Adamantios** [comment]
Another example of the RPC misbehaving:

```
Filter with id: '{{some number}}' does not exist.
```
